version: '3.8'

services:
  mysql:
    # image: mysql:latest
    build: 
      context: .
      dockerfile: Db/Dockerfile
    container_name: mysql-container
    # environment:
    #   MYSQL_ROOT_PASSWORD: 12345678
    ports:
      - 3307:3306
    volumes:
      - ./Db/Data:/var/lib/mysql

  webapi:
    build: 
      context: .
      dockerfile: api/Dockerfile
    container_name: api-container
    ports:
      - 8000:8000
    depends_on:
      - mysql
  
  webrazor:
    build:
      context: .
      dockerfile: client/Dockerfile
    container_name: web-container
    ports: 
      - 9001:9001
    depends_on:
      -  webapi